services:
  - type: web
    name: my-mern-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
