services:
  - type: web
    name: json-fake-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001  # Or use $PORT to dynamically use Render's provided port
